-- Pivot para Atributos
WITH
codPivot AS (
SELECT AFCODEMP AS EMPRESA, AFMATFUNC AS MATRICULA,
		MAX(CASE WHEN AFCODATRIB = 5 THEN AFVALOR END) AS LOCALIDADE,
		MAX(CASE WHEN AFCODATRIB = 47 THEN AFVALOR END) AS POSICAO,
		MAX(CASE WHEN AFCODATRIB = 41 THEN AFVALOR END) AS AREA,
		MAX(CASE WHEN AFCODATRIB = 43 THEN AFVALOR END) AS REPORT_FRANCA,
		MAX(CASE WHEN AFCODATRIB = 40 THEN AFVALOR END) AS TIPO_CONTRATO
  FROM ATRIBFUN
  WHERE AFCODATRIB IN (5, 47, 41, 43, 40)
  GROUP BY AFCODEMP, AFMATFUNC
			),
-- Pivot para Eventos
pivotEVEFUNC AS (

SELECT VACODEMP AS EMPRESA, VAMATFUNC AS MATRICULA,
       MAX(CASE WHEN VACODEVENT = 245 THEN VAVALEVENT END) AS NOTA_FISCAL,
       MAX(CASE WHEN VACODEVENT = 2630 THEN VAVALEVENT END) AS PRO_LABORE,
       MAX(CASE WHEN VACODEVENT = 4110 THEN VAVALEVENT END) AS ANTECIPACAO_LUCROS,
       MAX(CASE WHEN VACODEVENT = 11000 THEN VAVALEVENT END) AS SALARIO_MENSAL
	   
  FROM VALANO
  WHERE VACODEVENT IN (245, 2630, 4110, 11000)
  AND VACODFOLHA IN (1, 16, 32)
  AND VADTREFER = 201806
  GROUP BY VACODEMP, VAMATFUNC
			)
			SELECT
	CASE STTIPOSITU
		WHEN 'N' THEN 'ATIVO'
		WHEN 'A' THEN 'AFASTADO'
		WHEN 'F' THEN 'FERIAS' END AS SITUACAO,
	EMCODEMP    AS COD_EMPRESA,
	FUMATFUNC AS MATRICULA,
	FUNOMFUNC AS NOME,
	CONVERT(VARCHAR(11),CONVERT(DATE,CONVERT(VARCHAR(11),FUDTADMIS),112), 103) AS DATA_ADMISSAO,
	STDESCSITU	AS STATUS,
	AF.TIPO_CONTRATO,
	AF.LOCALIDADE,
	
		-- Tempo de Casa
	CONVERT(CHAR(2), DATEDIFF(DAY, CONVERT(DATE,CONVERT(VARCHAR(11),FUDTADMIS),112), GETDATE()) / 365) + ' Anos e ' +
	CONVERT(CHAR(2), DATEDIFF(MONTH, CONVERT(DATE,CONVERT(VARCHAR(11),FUDTADMIS),112), GETDATE()) % 12) + ' Meses' AS TEMPO_DE_CASA,
		-- Tempo de Casa
	
	CADESCARGO AS DESC_CARGO,
	AF.POSICAO,
	AF.REPORT_FRANCA,
	AF.AREA,
	CCDESCRIC AS DESC_CCUSTO,
	FUCENTRCUS AS CEN_CUSTO,
		
	-- REMUNERACAO
	ISNULL(VA.SALARIO_MENSAL,0) + ISNULL(VA.PRO_LABORE,0) + ISNULL(VA.ANTECIPACAO_LUCROS,0) + ISNULL(VA.NOTA_FISCAL,0) AS REMUNERACAO,
	VA.SALARIO_MENSAL,
	VA.PRO_LABORE,
	VA.ANTECIPACAO_LUCROS,
	VA.NOTA_FISCAL
	-- REMUNERACAO
		
FROM FUNCIONA
       INNER JOIN EMPRESAS ON EMCODEMP = FUCODEMP
	   INNER JOIN CARGOS ON CACODEMP = FUCODEMP AND CACODCARGO = FUCODCARGO
       INNER JOIN CENCUSTO ON CCCODEMP = FUCODEMP AND CCCODIGO = FUCENTRCUS
	   INNER JOIN SITUACAO ON STCODSITU = FUCODSITU
       LEFT JOIN codPivot AS AF ON AF.EMPRESA = FUCODEMP AND AF.MATRICULA = FUMATFUNC
       LEFT JOIN pivotEVEFUNC AS VA ON VA.EMPRESA = FUCODEMP AND VA.MATRICULA = FUMATFUNC
	WHERE STTIPOSITU <> 'R'
	AND FUCODEMP < 500
	AND AF.TIPO_CONTRATO NOT IN ('SOCIO A', 'SOCIO B') 
	ORDER BY AF.EMPRESA, FUNOMFUNC;