-- Pivot para Atributos
WITH 
codPivot AS (
SELECT AFCODEMP AS EMPRESA, AFMATFUNC AS MATRICULA,
		MAX(CASE WHEN AFCODATRIB = 5 THEN AFVALOR END) AS LOCALIDADE,
		MAX(CASE WHEN AFCODATRIB = 47 THEN AFVALOR END) AS POSICAO,
		MAX(CASE WHEN AFCODATRIB = 41 THEN AFVALOR END) AS AREA,
		MAX(CASE WHEN AFCODATRIB = 43 THEN AFVALOR END) AS REPORT_FRANCA,
		MAX(CASE WHEN AFCODATRIB = 40 THEN AFVALOR END) AS TIPO_CONTRATO
  FROM ATRIBFUN
  WHERE AFCODATRIB IN (5, 47, 41, 43, 40)
  GROUP BY AFCODEMP, AFMATFUNC
			),
-- Pivot para Eventos
pivotEVEFUNC AS (

SELECT VACODEMP AS EMPRESA, VAMATFUNC AS MATRICULA,
       MAX(CASE WHEN VACODEVENT = 3300 THEN VAVALEVENT END) AS SALDO_SALARIO,
       MAX(CASE WHEN VACODEVENT = 3350 THEN VAVALEVENT END) AS AVISO_INDENIZADO,
       MAX(CASE WHEN VACODEVENT = 3355 THEN VAVALEVENT END) AS ART_479,
       MAX(CASE WHEN VACODEVENT = 3390 THEN VAVALEVENT END) AS ART_477,
	   MAX(CASE WHEN VACODEVENT = 3400 THEN VAVALEVENT END) AS FERIAS_VENCIDAS,	   
       MAX(CASE WHEN VACODEVENT = 3405 THEN VAVALEVENT END) AS FERIAS_PROPORCIONAIS,	   
       MAX(CASE WHEN VACODEVENT = 3410 THEN VAVALEVENT END) AS FERIAS_IND,
       MAX(CASE WHEN VACODEVENT = 3415 THEN VAVALEVENT END) AS TERCO_FERIAS,
       MAX(CASE WHEN VACODEVENT = 3420 THEN VAVALEVENT END) AS _13_PROPORCIONAL,
       MAX(CASE WHEN VACODEVENT = 3425 THEN VAVALEVENT END) AS _13_IND,
       MAX(CASE WHEN VACODEVENT = 11520 THEN VAVALEVENT END) AS MULTA_50_FGTS   
	   
  FROM VALANO
  WHERE VACODEVENT IN (3300, 3350, 3355, 3390, 3400, 3405, 3410, 3415, 3420, 3425, 11520)
  AND VACODFOLHA = 5
  AND VADTREFER = 201803
  GROUP BY VACODEMP, VAMATFUNC
			)
			SELECT
	EMCODEMP    AS COD_EMPRESA,
	EMNOMEMP    AS EMPRESA,
	FUMATFUNC AS MATRICULA,
	FUNOMFUNC AS NOME,
	FUEMAIL		AS EMAIL,
	AF.TIPO_CONTRATO,
	STDESCSITU	AS STATUS,
	CASE STTIPOSITU
		WHEN 'R' THEN 'DESLIGADO' END AS SITUACAO,
	AF.LOCALIDADE,
	CASE FUSEXFUNC
		WHEN 'F' THEN 'FEMININO'
		WHEN 'M' THEN 'MASCULINO' END AS SEXO,
	CASE FUCODTIPOLOGRADOURO 
		WHEN 0 THEN ' ' 
		WHEN 2 THEN 'ALAMEDA' 
		WHEN 4 THEN 'AVENIDA' 
		WHEN 13 THEN 'ESTRADA' 
		WHEN 33 THEN 'RUA' 
		WHEN 36 THEN 'TRAVESSA' ELSE 'OUTROS' END + ' ' + FUENDERECO + ', ' +
		SUBSTRING(CONVERT(VARCHAR(5),FUNUMERO),1,LEN(FUNUMERO)) + ' - ' +
		SUBSTRING(CONVERT(VARCHAR(15),FUCOMPLEMENTO),1,LEN(FUCOMPLEMENTO)) AS ENDERECO,
	FUBAIRRO	AS BAIRRO,
	FUCPF		AS CPF,
	FUIDENTNUM	AS RG,
		SUBSTRING(CONVERT(VARCHAR(8),FUCTRABNUM),1,LEN(FUCTRABNUM)) + '/' + 
		SUBSTRING(CONVERT(VARCHAR(5),FUCTRABSER),1,LEN(FUCTRABNUM)) + '-' +
		SUBSTRING(CONVERT(CHAR(2),FUCTRABUF),1,2) AS CTPS,
		FUPISPASEP AS PIS,
	CASE FUESTCIVIL
		WHEN '1' THEN 'SOLTEIRO'
		WHEN '2' THEN 'CASADO'
		WHEN '3' THEN 'SEPARADO JUDICIALMENTE'
		WHEN '4' THEN 'DIVORCIADO'
		WHEN '5' THEN 'VIUVO'
		WHEN '6' THEN 'OUTROS'
		WHEN '7' THEN 'IGNORADO'  END AS ESTADO_CIVIL,
		CONVERT(VARCHAR(11),CONVERT(DATE,CONVERT(VARCHAR(11),FUDTNASC),112), 103) AS DATA_NASCIMENTO,
		CONVERT(VARCHAR(11),CONVERT(DATE,CONVERT(VARCHAR(11),FUDTADMIS),112), 103) AS DATA_ADMISSAO,
		CONVERT(VARCHAR(11),CONVERT(DATE,CONVERT(VARCHAR(11),OFDTINIOCO),112), 103) AS DATA_DEMISSÃO,

		-- Tempo de Casa
	CONVERT(CHAR(2), DATEDIFF(DAY, CONVERT(DATE,CONVERT(VARCHAR(11),FUDTADMIS),112), GETDATE()) / 365) + ' Anos e ' +
	CONVERT(CHAR(2), DATEDIFF(MONTH, CONVERT(DATE,CONVERT(VARCHAR(11),FUDTADMIS),112), GETDATE()) % 12) + ' Meses' AS TEMPO_DE_CASA,
		-- Tempo de Casa

	FUCENTRCUS AS CEN_CUSTO,
	CCDESCRIC AS DESC_CCUSTO,
	CADESCARGO AS DESC_CARGO,
	AF.POSICAO,
	AF.REPORT_FRANCA,
	AF.AREA,
	VA.SALDO_SALARIO,
	VA.AVISO_INDENIZADO,
	VA.ART_479,
	VA.ART_477,
	VA.FERIAS_VENCIDAS,
	VA.FERIAS_PROPORCIONAIS,
	VA.FERIAS_IND,
	VA.TERCO_FERIAS,
	VA._13_PROPORCIONAL,
	VA._13_IND,
	VA.MULTA_50_FGTS

FROM FUNCIONA
       INNER JOIN EMPRESAS ON EMCODEMP = FUCODEMP
	   INNER JOIN CARGOS ON CACODEMP = FUCODEMP AND CACODCARGO = FUCODCARGO
       INNER JOIN CENCUSTO ON CCCODEMP = FUCODEMP AND CCCODIGO = FUCENTRCUS
	   INNER JOIN SITUACAO ON STCODSITU = FUCODSITU
	   INNER JOIN OCORFUNC ON OFCODEMP = FUCODEMP AND OFMATFUNC = FUMATFUNC
       LEFT JOIN codPivot AS AF ON AF.EMPRESA = FUCODEMP AND AF.MATRICULA = FUMATFUNC
       LEFT JOIN pivotEVEFUNC AS VA ON VA.EMPRESA = FUCODEMP AND VA.MATRICULA = FUMATFUNC
	WHERE OFDTINIOCO BETWEEN 20180301 AND 20180331
	AND OFCODOCORR = 1004
	AND STDESCSITU <> 'TRANSFERENCIA S/ONUS P/CEDENTE'
	AND FUCODEMP < 500
	ORDER BY AF.EMPRESA, FUNOMFUNC;